[input]
html_selector = "main"
base_directory = "output"

[[input.files]]
path = "pages/about.html"
url = "/pages/about.html"
title = "About"

[[input.files]]
path = "cd-rip-guide.html"
url = "/cd-rip-guide.html"
title = "CD Rip Guide"

[[input.files]]
path = "dvd-rip-guide.html"
url = "/dvd-rip-guide.html"
title = "DVD Rip Guide"

[[input.files]]
path = "eac-install-guide.html"
url = "/eac-install-guide.html"
title = "Exact Audio Copy Install and Setup Guide"

[[input.files]]
path = "vinyl-rip-guide.html"
url = "/vinyl-rip-guide.html"
title = "Vinyl Rip Guide"

[[input.files]]
path = "gt4-100.html"
url = "/gt4-100.html"
title = "Gran Turismo 4 - The Journey to 100%"

[[input.files]]
path = "my-first-post.html"
url = "/my-first-post.html"
title = "My First Post"
